#!/usr/bin/env bash
# Builds Trailmix.app: a double-clickable launcher for Finder, the Dock or Spotlight.
# It starts the background server if needed and opens Trailmix in its own window.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP="$ROOT/Trailmix.app"

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

cat >"$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>CFBundleName</key><string>Trailmix</string>
  <key>CFBundleDisplayName</key><string>Trailmix</string>
  <key>CFBundleIdentifier</key><string>local.trailmix.launcher</string>
  <key>CFBundleVersion</key><string>1.0</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleExecutable</key><string>Trailmix</string>
  <key>CFBundleIconFile</key><string>AppIcon</string>
  <key>LSMinimumSystemVersion</key><string>13.0</string>
</dict></plist>
PLIST

cat >"$APP/Contents/MacOS/Trailmix" <<SH
#!/bin/bash
# Generated by scripts/make-mac-app.sh. Points at: $ROOT
LOG="$ROOT/backend/data/logs/launcher.log"
mkdir -p "\$(dirname "\$LOG")"
if ! "$ROOT/trailmix" open >>"\$LOG" 2>&1; then
  osascript -e "display alert \"Trailmix couldn't start\" message \"\$(tail -n 4 "\$LOG" | sed 's/\x1b\[[0-9;]*m//g' | tr '\"' \"'\")\" as critical"
fi
SH
chmod +x "$APP/Contents/MacOS/Trailmix"

"$ROOT/scripts/make-icon.sh" "$APP/Contents/Resources/AppIcon.icns" || true

touch "$APP"  # nudge Finder to pick up the icon
echo "Built $APP"
echo "Drag it to your Dock or Applications folder (it keeps working from there)."
